# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby
  heroku: circleci/heroku@1.0.1

workflows:
  version: 2
  rspec-rubocop-deploy:
   jobs:
     - rspec
     - rubocop:
         requires:
           - rspec
     - deploy:
         requires:
           - rubocop
         filters:
           branches:
             only: master

jobs: 
  rspec:
    working_directory: ~/zadeploy/profile_app 
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node
    steps: 
      - checkout
      - run: 
          name: install dependencies
          command: gem update --system && gem install bundler && bundle install --path vendor/bundle
      - ruby/bundle-install
      - run:
          name: run rspec via bundle
          command: bundle exec rspec
  rubocop:
    working_directory: ~/zadeploy/profile_app
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node
    steps: 
      - checkout
      - run: 
          name: install dependencies
          command: gem update --system && gem install bundler && bundle install --path vendor/bundle
      - ruby/bundle-install
      - run:
          name: run rubocop via bundle
          command: bundle exec rubocop --auto-correct
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
# or we can use config below
#    working_directory: ~/zadeploy/profile_app
#    docker:
#      - image: circleci/ruby:2.6.3-stretch-node
#    steps: 
#      - checkout
#      - run:
#          name: deploy to heroku with git
#          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master 
